version: '3.8'

services:
  app:
    build: .
    container_name: vegetarian_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: vegetarian_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge